# @package _global_

defaults:
  - /commands/rlbench/evals/_base@_here_
  - override /model: taxpose
  - override /object_class: phone_on_base
  - override /relationship: place
  - _self_

break_symmetry: False

model:
  break_symmetry: False

dm:
  train_dset:
    num_points: 256
