# @package _global_

defaults:
  - /commands/rlbench/evals/_base@_here_
  - override /model: taxpose
  - override /object_class: stack_wine
  - override /relationship: place
  - _self_

break_symmetry: True

dm:
  train_dset:
    num_points: 256
