# @package _global_

defaults:
  - /commands/mfi/_train@_here_
  - override /model: taxpose
  - override /task: waterproof
  - override /phase: place
  - _self_

break_symmetry: False

dm:
  train_dset:
    demo_dset:
      dataset_root: /home/mfi/repos/rtc_vision_toolbox/data/train_data/taxpose/wp-grasp-place/place/train
      min_num_points: 1024
      synthetic_occlusion: True
      occlusion_cfg:
        action_ball_occlusion: True
        action_ball_radius: 0.04
        anchor_ball_occlusion: True
        anchor_ball_radius: 0.1
        downsample_type: 2N_random_fps
    action_rot_sample_method: "quat_uniform"
    anchor_rot_sample_method: "random_flat_upright"
    translation_variance: 1.0
  val_dset:
    demo_dset:
      dataset_root: /home/mfi/repos/rtc_vision_toolbox/data/train_data/taxpose/wp-grasp-place/place/test
      min_num_points: 1024
    action_rot_sample_method: "quat_uniform"
    anchor_rot_sample_method: "random_flat_upright"
  test_dset:
    demo_dset:
      dataset_root: /home/mfi/repos/rtc_vision_toolbox/data/train_data/taxpose/wp-grasp-place/place/test
      min_num_points: 1024
    action_rot_sample_method: "quat_uniform"
    anchor_rot_sample_method: "random_flat_upright"

training:
  batch_size: 6
  max_epochs: 2000

wandb:
  entity: oadonca
  project: rtc
  group: waterproof_place