# @package _global_

defaults:
  - /commands/mfi/_train@_here_
  - override /model: taxpose
  - override /task: waterproof
  - override /phase: place
  - _self_

break_symmetry: False

dm:
  train_dset:
    demo_dset:
      dataset_root: /home/mfi/repos/rtc_vision_toolbox/data/demonstrations/08-12-wp/learn_data/train
      min_num_points: 2048
      synthetic_occlusion: False
      occlusion_cfg:
        action_ball_occlusion: True
        action_ball_radius: 0.02
        anchor_ball_occlusion: True
        anchor_ball_radius: 0.03
        downsample_type: random_0.5
    action_rot_sample_method: "quat_uniform"
    anchor_rot_sample_method: "random_upright"
    translation_variance: 1.0
  val_dset:
    demo_dset:
      dataset_root: /home/mfi/repos/rtc_vision_toolbox/data/demonstrations/08-12-wp/learn_data/test
      min_num_points: 2048
    action_rot_sample_method: "quat_uniform"
    anchor_rot_sample_method: "random_upright"
  test_dset:
    demo_dset:
      dataset_root: /home/mfi/repos/rtc_vision_toolbox/data/demonstrations/08-12-wp/learn_data/test
      min_num_points: 2048
    action_rot_sample_method: "quat_uniform"
    anchor_rot_sample_method: "random_upright"

training:
  batch_size: 6
  max_epochs: 4000

wandb:
  entity: shobhitagg
  project: rtc
  group: waterproof_place