# task: mug_place
name: usb_place
action_class: 0
anchor_class: 1
cloud_type: teleport
softmax_temperature: 1
weight_normalize: l1
action_name: usb
anchor_name: nist_board
checkpoint_file_action: ${hydra:runtime.cwd}/trained_models/pretraining_mug_embnn_weights.ckpt
checkpoint_file_anchor: ${hydra:runtime.cwd}/trained_models/pretraining_rack_embnn_weights.ckpt
