[project]
name = "taxpose"
version = "0.1.0"
description = "TAX-Pose: Task-Specific Cross-Pose Estimation for Robot Manipulation"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE.txt"}
authors = [
  {email = "chuerp@andrew.cmu.edu", name = "Chuer Pan"},
  {email = "bokorn@andrew.cmu.edu", name = "Brian Okorn"},
  {email = "haolunz@andrew.cmu.edu", name = "Harry Zhang"},
  {email = "baeisner@andrew.cmu.edu", name = "Ben Eisner"},
  {email = "dheld@andrew.cmu.edu", name = "David Held"},
]
dependencies = [
  "dgl ~= 1.0",
  "dglgo ~= 0.0.2",
  "pybullet",
  "pyg_lib ~= 0.1.0; sys_platform = 'linux",
  "rpad-partnet-mobility-utils @ git+https://github.com/r-pad/partnet_mobility_utils.git",
  "rpad-pyg @ git+https://github.com/r-pad/pyg_libs.git#46d20b5f32ce71e78413a0789def155ba1f88b1e",
  "torch ~= 1.13",
  "torch_cluster ~= 1.6.0",
  "torch-geometric ~= 2.2.0",
  "torch_scatter ~= 2.1.0",
  "torch_sparse ~= 0.6.16",
  "torch_spline_conv ~= 1.2.1",
]

[build-system]
requires = [
  "setuptools >= 62.3.2",
  "setuptools-scm",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
develop = [
  "pytest",
  "black >= 22.3.0",
  "isort",
  "mypy",
  "pylint",
  "autoflake",
  "pre-commit",
  "jupyterlab",
]
build_docs = [
  "mkdocs-material",
  "mkdocstrings[python]",
]


# This is required to allow us to have notebooks/ at the top level.
[tool.setuptools]
packages = ["taxpose"]

[tool.setuptools.package-data]
taxpose = ["py.typed"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.8
warn_return_any = true
warn_unused_configs = true
mypy_path = "src"
namespace_packages = true
explicit_package_bases = true

# # Uncomment this when you have imports for mypy to ignore.
# [[tool.mypy.overrides]]
# module = [
# ]
# ignore_missing_imports = true
