# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: taxpose
  - override /task: put_toilet_roll_on_stand
  - override /phase: place
  - _self_

break_symmetry: True

dm:
  train_dset:
    num_points: 256
