# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: mlat_s256_vnn
  - override /task: put_toilet_roll_on_stand
  - override /phase: place
  - _self_

break_symmetry: True
