# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose
  - override /task: put_toilet_roll_on_stand
  - override /phase: grasp
  - _self_

break_symmetry: True
