
# This is the general structure of the datamodule for NDF tasks.

train_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${object_class.name}
    n_demos: 10
    action_class: ${task.action_class}
    anchor_class: ${task.anchor_class}
    cached: true

val_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${object_class.name}
    n_demos: 1
    action_class: ${task.action_class}
    anchor_class: ${task.anchor_class}
    cached: true

test_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}
    task_name: ${object_class.name}
    n_demos: 1
    action_class: ${task.action_class}
    anchor_class: ${task.anchor_class}
    cached: true
