defaults:
  - rlbench/_default@_here_
  - _self_

# Dataset Settings
train_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 0
      - 1
      - 2
      - 3
      - 4
      # - 5 # This episode is broken, too few points on the peg.
      # - 6  # This episode is broken, too few points on the peg.
      - 7

val_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 8
      - 9

test_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 0
