defaults:
  - rlbench/_default@_here_
  - _self_

# Dataset Settings
train_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 0

val_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 1

test_dset:
  demo_dset:
    dataset_type: ${benchmark.name}
    episodes:
      - 2
