# @package _global_

defaults:
  - /commands/rlbench/_eval_base@_here_
  - override /model: mlat_s256_vnn
  - override /object_class: place_hanger_on_rack
  - override /relationship: place
  - _self_

break_symmetry: False

model:
  break_symmetry: False

dm:
  train_dset:
    num_points: 256
