# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: mlat_s256_vnn
  - override /object_class: stack_wine
  - override /relationship: place
  - _self_

break_symmetry: True

# Dataset Settings
dm:
  train_dset:
    demo_dset:
      dataset_type: ${benchmark.name}
      episodes:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9

  val_dset:
    demo_dset:
      episodes:
        - 10
