# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose
  - override /task: stack_wine
  - override /phase: place
  - _self_

break_symmetry: True

# Dataset Settings
dm:
  train_dset:
    demo_dset:
      dataset_type: ${benchmark.name}
      episodes:
        - 0

  val_dset:
    demo_dset:
      episodes:
        - 10
