# @package _global_

defaults:
  - /commands/rlbench/_eval_taxposed@_here_
  - override /task:  insert_onto_square_peg
  - override /model@grasp_model: taxposed
  - override /model@place_model: taxposed
  - _self_

break_symmetry: False

training:
  init_cond_x: True
  freeze_embnn: True
  freeze_residual_flow: True
  freeze_z_embnn: True

  load_from_checkpoint: True
  checkpoint_file: null

dm:
  train_dset:
    num_points: 256

num_trials: 100
headless: True

resources:
  num_workers: 1
