# @package _global_

defaults:
  - /commands/rlbench/_eval_base@_here_
  - override /model: taxpose
  - override /object_class: insert_onto_square_peg
  - override /relationship: place
  - _self_

break_symmetry: True

model:
  break_symmetry: True

dm:
  train_dset:
    num_points: 256
