# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: mlat_s256_vnn
  - override /task: insert_onto_square_peg
  - override /phase: place
  - _self_

break_symmetry: True

model:
  break_symmetry: True

dm:
  train_dset:
    num_points: 256
