# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose
  - override /task: insert_onto_square_peg
  - override /phase: place
  - _self_

break_symmetry: True

dm:
  train_dset:
    num_points: 256
