# @package _global_

defaults:
  - /commands/_train_rlbench@_here_
  - override /model: taxpose
  - override /object_class: insert_onto_square_peg
  - override /relationship: place
  - _self_

break_symmetry: False
