# @package _global_

defaults:
  - /commands/_train_rlbench@_here_
  - override /model: taxpose
  - override /object_class: put_toilet_roll_on_stand
  - override /relationship: place
  - _self_

break_symmetry: False
