
# This is the general structure of the datamodule for NDF tasks.

train_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}/${task.name}/train_data/renders
    dataset_indices: ???
    num_demo: ???
    min_num_points: 1024
    cloud_type: ${task.cloud_type}
    action_class: ${task.action_class}
    anchor_class: ${task.anchor_class}
    min_num_cameras: 4
    max_num_cameras: 4

val_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}/${task.name}/test_data/renders
    dataset_indices: ???
    num_demo: ???
    min_num_points: ${...train_dset.demo_dset.min_num_points}
    cloud_type: ${...train_dset.demo_dset.cloud_type}
    action_class: ${...train_dset.demo_dset.action_class}
    anchor_class: ${...train_dset.demo_dset.anchor_class}
    min_num_cameras: ${...train_dset.demo_dset.min_num_cameras}
    max_num_cameras: ${...train_dset.demo_dset.max_num_cameras}

test_dset:
  demo_dset:
    dataset_root: ${benchmark.dataset_root}/${task.name}/test_data/renders
    dataset_indices: ???
    num_demo: ???
    min_num_points: ${...train_dset.demo_dset.min_num_points}
    cloud_type: ${...train_dset.demo_dset.cloud_type}
    action_class: ${...train_dset.demo_dset.action_class}
    anchor_class: ${...train_dset.demo_dset.anchor_class}
    min_num_cameras: ${...train_dset.demo_dset.min_num_cameras}
    max_num_cameras: ${...train_dset.demo_dset.max_num_cameras}
