# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: mlat_s256_vnn
  - override /task: phone_on_base
  - override /phase: place
  - _self_

break_symmetry: False

model:
  break_symmetry: False

dm:
  train_dset:
    num_points: 256
