
# This is the general structure of the datamodule for NDF tasks.

root: /data/ndf
task: ???  # This is one of the 6 tasks - depends on the action class.

train_dset:
  dataset_type: ndf_pretraining
  dataset_root: ${..root}
  dataset_indices: null
  cloud_type: init
  action_class: 0
  num_points: 1024

val_dset:
  dataset_type: ${..train_dset.dataset_type}
  dataset_root: ${..root}
  dataset_indices: ${..train_dset.dataset_indices}
  cloud_type: ${..train_dset.cloud_type}
  action_class: ${..train_dset.action_class}
  num_points: ${..train_dset.num_points}

test_dset:
  dataset_type: ${..train_dset.dataset_type}
  dataset_root: ${..root}
  dataset_indices: ${..train_dset.dataset_indices}
  cloud_type: ${..train_dset.cloud_type}
  action_class: ${..train_dset.action_class}
  num_points: ${..train_dset.num_points}
