action_plane_occlusion: False
action_plane_standoff: 0.04
action_ball_occlusion: False
action_ball_radius: 0.1

anchor_plane_occlusion: False
anchor_plane_standoff: 0.04
anchor_ball_occlusion: False
anchor_ball_radius: 0.1

occlusion_class: 0
occlusion_prob: 0.5
downsample_type: fps