defaults:
  - taxpose_base

arbitrary:
  grasp: ${hydra:runtime.cwd}/trained_models/ndf/${task.name}/arbitrary/grasp.ckpt
  place: ${hydra:runtime.cwd}/trained_models/ndf/${task.name}/arbitrary/place.ckpt
upright:
  grasp: ${hydra:runtime.cwd}/trained_models/ndf/${task.name}/upright/grasp.ckpt
  place: ${hydra:runtime.cwd}/trained_models/ndf/${task.name}/upright/place.ckpt
