# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose
  - override /object_class: stack_wine
  - override /relationship: place
  - _self_

break_symmetry: True
