name: put_hanger_on_rack
action_class: 0
anchor_class: 1
cloud_type: teleport
softmax_temperature: 1
weight_normalize: l1
action_name: hanger
anchor_name: hanger_rack
checkpoint_file_action: null
checkpoint_file_anchor: null
