name: solve_puzzle_place
action_class: 0
anchor_class: 1
cloud_type: teleport
softmax_temperature: 1
weight_normalize: l1
action_name: puzzle_piece
anchor_name: puzzle
checkpoint_file_action: null
checkpoint_file_anchor: null
