# @package _global_

defaults:
  - /commands/rlbench/_eval@_here_
  - override /model: mlat_s256_vnn
  - override /task: stack_wine
  - override /phase: place
  - _self_

break_symmetry: True

model:
  break_symmetry: True

checkpoints:
  place: r-pad/taxpose/model-9irzbsw6:v0

dm:
  train_dset:
    demo_dset:
      episodes:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9

  val_dset:
    demo_dset:
      episodes:
        - 10
