defaults:
  # hydra default which removes ndf from the tree
  - _self_
  - dataset@dm: ${benchmark}/${object_class}_${relationship}


dm:

  train_dset:
    demo_dset: ???

    num_points: 1024
    rotation_variance: 3.141592653589793
    translation_variance: 0.5
    dataset_size: 1000
    angle_degree: 180
    synthetic_occlusion: False
    ball_radius: null
    plane_occlusion: False
    ball_occlusion: False
    plane_standoff: null
    occlusion_class: 2
    symmetric_class: null
    overfit: False
    num_overfit_transforms: 3
    gripper_lr_label: False

  val_dset:
    demo_dset: ???
    # extra parameters...
    num_points: ${..train_dset.num_points}
    rotation_variance: ${..train_dset.rotation_variance}
    translation_variance: ${..train_dset.translation_variance}
    dataset_size: ${..train_dset.dataset_size}
    angle_degree: ${..train_dset.angle_degree}
    synthetic_occlusion: ${..train_dset.synthetic_occlusion}
    ball_radius: ${..train_dset.ball_radius}
    plane_occlusion: ${..train_dset.plane_occlusion}
    ball_occlusion: ${..train_dset.ball_occlusion}
    plane_standoff: ${..train_dset.plane_standoff}
    occlusion_class: ${..train_dset.occlusion_class}
    symmetric_class: ${..train_dset.symmetric_class}
    overfit: ${..train_dset.overfit}
    num_overfit_transforms: ${..train_dset.num_overfit_transforms}
    gripper_lr_label: ${..train_dset.gripper_lr_label}

  test_dset:
    demo_dset: ???
    # extra parameters...
