# Logging Settings
job_type: pretraining_${benchmark.name}_${object_class.name}
image_logging_period: 1000

defaults:
  - benchmark: ndf
  - object_class: mug
  - _logging
  - _self_

seed: 0


training:
  dataset:
    root: ${hydra:runtime.cwd}/data/mug_place/train_data/renders
    pretraining_data_path: /home/beisner/code/multi_project/taxpose/third_party/ndf_robot/src/ndf_robot/data
    num_points: 1024
    dataset_index: None
    cloud_class: 0 # 0 for mug, 1 for rack, 2 for gripper
    cloud_type: init
    overfit: false
    obj_class: ${object_class.name}

  batch_size: 8
  epochs: 100

resources:
  num_workers: 4
  gpus:
    - 0

wandb:
  group: Null


# Network Settings
emb_dims: 512
emb_nn: dgcnn
inital_sampling_ratio: 1
normalize_features: true

# Loss Settings
con_weighting: dist
l2_reg_weight: 0
temperature: 0.1

# Training Settings
checkpoint_file: Null
lr: 1e-4
