

job_type: train_${task.name}

defaults:
  - _self_
  - _logging
  - datamodule  # This loops in the dataset.
  - benchmark: ndf # {ndf, rlbench}
  - object_class: mug # {mug, bottle, bowl}
  - relationship: place # {place, grasp}
  - pose_dist: upright # {upright, arbitrary}
  - model: release
  - task: ${object_class}_${relationship}
  - optional checkpoints/ndf@checkpoints: ${object_class}/${model}
  - checkpoints/pretraining@checkpoints.pretraining

resources:
  num_workers: 8

training:
  batch_size: 8
  max_epochs: 500

  sigmoid_on: True

  # Optimizer Settings
  lr: 1e-4

  # Loss Settings
  flow_supervision: both
  displace_loss_weight: 1
  direct_correspondence_loss_weight: 1
  consistency_loss_weight: 0.1

  # Checkpoint Settings
  load_from_checkpoint: False
  checkpoint_file: null

  # Visualization Settings
  image_logging_period: 100
  log_every_n_steps: 100
  check_val_every_n_epoch: 5

wandb:
  group: Null

pretraining:
  mode: nce_loss
  checkpoint_file_action: ${checkpoints.pretraining.${model.emb_nn}.${pretraining.mode}.${task.action_name}}
  checkpoint_file_anchor: ${checkpoints.pretraining.${model.emb_nn}.${pretraining.mode}.${task.anchor_name}}

seed: 0
break_symmetry: False
