# @package _global_

defaults:
  - /commands/_train_ndf@_here_
  - _self_

dm:
  train_dset:
    rotation_variance: 1e-4
    translation_variance: 1e-4

  val_dset:
    rotation_variance: 3.1415
    translation_variance: 0.5
