# @package _global_

defaults:
- /eval_rlbench.yaml
- override /model: taxpose_tc
- override /task: pick_and_lift
- _self_

# Make sure this one has rgb features.
model:
  feature_channels: 3

policy_spec:
  include_rgb_features: True
