# @package _global_

defaults:
  - /train_ndf
  - override /benchmark: mfi
  - _self_

break_symmetry: True

resources:
  num_workers: 16

max_epochs: 375
batch_size: 3

training:
  check_val_every_n_epoch: 10
  log_every_n_steps: 100
