# @package _global_

defaults:
  - /commands/rlbench/_train@_here_
  - override /model: taxpose
  - override /task: solve_puzzle
  - override /phase: place
  - _self_

break_symmetry: False

model:
  break_symmetry: False

dm:
  train_dset:
    num_points: 256
