# @package _global_

defaults:
  - /commands/ndf/_eval@_here_
  - override /model: mlat_s256_vnn
  - override /object_class: mug
  - override /pose_dist: upright
  - _self_

break_symmetry: False
model:
  break_symmetry: False
