# @package _global_

defaults:
  - /train_ndf
  - override /benchmark: rlbench
  - _self_

benchmark:
  dataset_root: /data/rlbench

log_dir: /opt/logs

wandb:
  artifact_dir: /opt/artifacts

break_symmetry: False

resources:
  num_workers: 16

max_epochs: 375
batch_size: 6

pretraining:
  mode: none

training:
  check_val_every_n_epoch: 10
  log_every_n_steps: 100

dm:
  train_dset:
    num_points: 256
