# @package _global_

defaults:
  - /train_ndf
  - _self_

benchmark:
  dataset_root: /data/ndf

log_dir: /opt/logs

wandb:
  artifact_dir: /opt/artifacts

resources:
  num_workers: 16

training:
  epochs: 200
  batch_size: 4
  check_val_every_n_epoch: 10
  log_every_n_steps: 100
