dgcnn:
  nce_loss:
    # These got retrained!
    # gripper: ${hydra:runtime.cwd}/trained_models/pretraining_gripper_embnn_weights.ckpt
    gripper: r-pad/taxpose/model-wajnzcwn:v0
    # mug: ${hydra:runtime.cwd}/trained_models/pretraining_mug_embnn_weights.ckpt
    mug: r-pad/taxpose/model-f81p2p5d:v0
    # rack: ${hydra:runtime.cwd}/trained_models/pretraining_rack_embnn_weights.ckpt
    rack: r-pad/taxpose/model-1on3wem2:v0
    # bottle: ${hydra:runtime.cwd}/trained_models/pretraining_bottle_embnn_weights.ckpt
    bottle: r-pad/taxpose/model-nogq98i9:v0
    # bowl: ${hydra:runtime.cwd}/trained_models/pretraining_bowl_embnn_weights.ckpt
    bowl: r-pad/taxpose/model-i7e35k1f:v0
    # slab: ${hydra:runtime.cwd}/trained_models/pretraining_slab_embnn_weights.ckpt
    slab: r-pad/taxpose/model-ysgwf55q:v0
  none:
    gripper: null
    mug: null
    rack: null
    wine: null
    wine_rack: null
    bottle: null
    bowl: null
    slab: null
vn_dgcnn:
  nce_loss:
    # 0
    # mug: /home/beisner/code/multi_project/taxpose/outputs/2023-05-22/17-09-00/embedding_pretraining_mug/2eakon6k/checkpoints/embnn_callback_epoch_2_global_step_33000.ckpt
    # # 1
    # rack: /home/beisner/code/multi_project/taxpose/outputs/2023-05-23/14-31-55/embedding_pretraining_mug/wcdwkh8r/checkpoints/embnn_callback_epoch_999_global_step_13000.ckpt
    # # 2
    # gripper: /home/beisner/code/multi_project/taxpose/outputs/2023-05-23/14-31-58/embedding_pretraining_mug/1m959icc/checkpoints/embnn_callback_epoch_999_global_step_13000.ckpt
    gripper: r-pad/taxpose/model-3bvf82th:v0
    mug: r-pad/taxpose/model-p3fluqtg:v0
    rack: r-pad/taxpose/model-kxc51apt:v0
    bottle: r-pad/taxpose/model-x3c82iam:v0
    bowl: r-pad/taxpose/model-qbtkzw5y:v0
    slab: r-pad/taxpose/model-tmymvff2:v0

  none:
    gripper: null
    mug: null
    rack: null
    wine: null
    wine_rack: null
    bottle: null
    bowl: null
    slab: null
